title: Services
description: |
    CCV provides computing infrastructure, consulting, and support to the Brown
    Community. We have HPC specialists, data scientists, and research software engineers
    available to work with researchers. We frequently partner with researchers on
    projects that may span weeks, months, or years. These partnerships can in some
    cases involve a researcher using grant funds to support one of our data scientists
    or research software engineers.
call-for-action:
  text: See our rates
  href: /rates

